name: Deploy to Hostinger

on:
  push:
    branches:
      - master  # Déclenchement lorsque vous poussez sur la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Node.js pour le front-end
    - name: Set up Node.js
      if: ${{ contains(github.repository, 'ker_frontend') }}
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Version de Node.js requise pour votre projet

    # Étape 3 : Installer les dépendances et construire le front-end
    - name: Install dependencies and build
      if: ${{ contains(github.repository, 'ker_frontend') }}
      run: |
        npm install
        npm run build

    # Étape 4 : Déployer les fichiers du front-end sur le serveur Hostinger
    - name: Deploy front-end
      if: ${{ contains(github.repository, 'ker_frontend') }}
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        rsync -avz -e "ssh -i private_key.pem" dist/ u931933414@145.223.35.146:/home/u931933414/public_html/
        rm private_key.pem

    # Étape 5 : Déployer le back-end
    - name: Deploy back-end
      if: ${{ contains(github.repository, 'ker_backend') }}
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        rsync -avz -e "ssh -i private_key.pem" . u931933414@145.223.35.146:/home/u931933414/backend/
        ssh -i private_key.pem u931933414@145.223.35.146 "cd /home/u931933414/backend && npm install && pm2 restart all"
        rm private_key.pem
