name: Deploy to Hostinger

on:
  push:
    branches:
      - master  # Déclenchement lorsque vous poussez sur la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Node.js pour le front-end
    - name: Set up Node.js
      if: ${{ contains(github.repository, 'ker_frontend') }}
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Version de Node.js requise pour votre projet

    # Étape 3 : Installer les dépendances et construire le front-end
    - name: Install dependencies and build
      if: ${{ contains(github.repository, 'ker_frontend') }}
      run: |
        npm install
        npm run build
