name: Deploy to Hostinger

on:
  push:
    branches:
      - master  # Déclenchement lorsque vous poussez sur la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Node.js pour le front-end
    - name: Set up Node.js
      if: ${{ contains(github.repository, 'ker_frontend') }}
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Version de Node.js requise pour votre projet

    # Étape 3 : Installer les dépendances et construire le front-end
    - name: Install dependencies and build
      if: ${{ contains(github.repository, 'ker_frontend') }}
      run: |
        npm install
        npm run build

    # Étape 4 : Configurer la clé SSH et la connexion
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 145.223.35.146 >> ~/.ssh/known_hosts  # Ajoute l'hôte SSH à la liste des hôtes connus

    # Étape 5 : Déployer les fichiers du front-end sur le serveur Hostinger
    - name: Deploy front-end
      if: ${{ contains(github.repository, 'ker_frontend') }}
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" dist/ u931933414@145.223.35.146:/home/u931933414/domains/kerapp.fr/public_html/

    # Étape 6 : Déployer le back-end
    - name: Deploy back-end
      if: ${{ contains(github.repository, 'ker_backend') }}
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" . u931933414@145.223.35.146:/home/u931933414/domains/kerapp.fr/backend/
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no u931933414@145.223.35.146 "cd /home/u931933414/backend && npm install && pm2 restart all"
